options:
  zone:
    default: example.com
    description: The DNS root zone for this manager
    type: string
  sas:
    default: ""
    description: The location of the SAS server
    type: string
  enum:
    default: ""
    description: The location of the ENUM server
    type: string
