options:
  turn_workaround: 
    default: ""
    description: TURN workaround password, used by faulty WebRTC clients
    type: string
  repo:
    default: http://repo.cw-ngv.com/stable
    description: The location of the repo server
    type: string
