options:
  zone:
    description: The DNS root zone for this service
    type: string
  sas:
    default: ""
    description: The location of the SAS server
    type: string
  cdf:
    default: ""
    description: The location of the CDF to bill to
    type: string 
  repo:
    default: http://repo.cw-ngv.com/juju-clearwater-1/
    description: The location of the repo server
    type: string
